### ISSUE TITLE
"Data too long" and "Invalid copy offset" when decoding stream.

### ISSUE THREAD

**Issue by rodo-r2r** [brantburnett/Snappier#25]
Hi,

I have a ~500mb snappy compressed (generated from Snappy.NET) file which I am unable to decompress with Snappier.
Decoding the file works fine in Snappy.NET, and with golang/snappy.

I fixed a bunch of bugs in Snappier trying to diagnose this (see #24), now am a bit stuck.

To load the file I'm using:
```
  using var compressed = File.OpenRead(@"c:\path\to\file.snappy");   // 515mb fails.
  using var decompressed = new MemoryStream();
  using (var decompressor = new SnappyStream(compressed, CompressionMode.Decompress, true))
  {
      decompressor.CopyTo(decompressed);
  }
```

And getting the following error.
```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Data too long
  Source=Snappier
  StackTrace:
   at Snappier.Internal.SnappyDecompressor.ThrowInvalidDataException(String message) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 543
   at Snappier.Internal.SnappyDecompressor.AppendFromSelf(Byte* buffer, UInt32 copyOffset, Int64 length, SByte* pshufbFillPatterns) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 574
   at Snappier.Internal.SnappyDecompressor.DecompressAllTags(ReadOnlySpan`1 inputSpan) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 371
   at Snappier.Internal.SnappyDecompressor.Decompress(ReadOnlySpan`1 input) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 63
   at Snappier.Internal.SnappyStreamDecompressor.Decompress(Span`1 buffer) in C:\src\Snappier\Snappier\Internal\SnappyStreamDecompressor.cs:line 120
   at Snappier.SnappyStream.ReadCore(Span`1 buffer) in C:\src\Snappier\Snappier\SnappyStream.cs:line 185
   at Snappier.SnappyStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\src\Snappier\Snappier\SnappyStream.cs:line 154
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Snappier.Tests.SnappyStreamTests.LoadEurope() in C:\src\Snappier\Snappier.Tests\SnappyStreamTests.cs:line 120
```

Any idea what could be causing this?
Sadly I can't provide the file causing the issue, though I have a similar file (~130mb) which works fine.

While trying to produce a test case I was able to come up with:
```
        [Fact]
        public void BigStream()
        {
            // Test to trigger "Invalid copy offset" error

            // Generate 6mb of fairly compressable, but not totally repeated, data.
            // 5mb doesn't cause an error. Purely incrementing values don't cause an error.
            var rawBytes = new byte[6_000_000];
            for (int i = 0; i < rawBytes.Length; i++)
            {
                rawBytes[i] = (byte)(i * i % 0xff);
            }

            using var output = new MemoryStream();
            using (var compressor = new SnappyStream(output, CompressionMode.Compress, true))
            {
                using var mem = new MemoryStream(rawBytes);
                mem.CopyTo(compressor);
            }

            output.Position = 0;

            byte[] decompressedBytes;
            using (var decompressor = new SnappyStream(output, CompressionMode.Decompress, true))
            {
                using var mem = new MemoryStream(rawBytes);
                decompressor.CopyTo(mem);
                decompressedBytes = mem.ToArray();
            }

            Assert.Equal(rawBytes.Length, decompressedBytes.Length);
            Assert.Equal(rawBytes, decompressedBytes);
        }

```

Which triggers a different (but likely related?) error.

```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Invalid copy offset
  Source=Snappier
  StackTrace:
   at Snappier.Internal.SnappyDecompressor.ThrowInvalidDataException(String message) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 543
   at Snappier.Internal.SnappyDecompressor.AppendFromSelf(Byte* buffer, UInt32 copyOffset, Int64 length, SByte* pshufbFillPatterns) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 570
   at Snappier.Internal.SnappyDecompressor.DecompressAllTags(ReadOnlySpan`1 inputSpan) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 371
   at Snappier.Internal.SnappyDecompressor.Decompress(ReadOnlySpan`1 input) in C:\src\Snappier\Snappier\Internal\SnappyDecompressor.cs:line 63
   at Snappier.Internal.SnappyStreamDecompressor.Decompress(Span`1 buffer) in C:\src\Snappier\Snappier\Internal\SnappyStreamDecompressor.cs:line 120
   at Snappier.SnappyStream.ReadCore(Span`1 buffer) in C:\src\Snappier\Snappier\SnappyStream.cs:line 185
   at Snappier.SnappyStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\src\Snappier\Snappier\SnappyStream.cs:line 154
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Snappier.Tests.SnappyStreamTests.BigStream() in C:\src\Snappier\Snappier.Tests\SnappyStreamTests.cs:line ```

Note the "Invalid copy offset" vs "Data too long" messages.

**Comment by brantburnett** [comment]
@rodo-r2r I have a fix in place for the second error you found, it may be the cause of the first. I'm just going to try to write a more targeted unit test before I merge it. Can you try this commit with your test file to see what happens? https://github.com/brantburnett/Snappier/commit/fd92ec78d7cef10f404aa3eb4197edc0540869d3

**Comment by rodo-r2r** [comment]
Yay! This fixes both errors listed above.
Thanks for getting to this so quickly.

**Comment by brantburnett** [comment]
I’ll finish it up and get a new beta package on NuGet by tomorrow. Thanks!!!
